Revert "Merge develop into #209 (#222)"
This reverts commit bfdbd93e52380882460b2d298c054183c7b5273a.

diff --git a/.github/workflows/document.yaml b/.github/workflows/document.yaml
--- a/.github/workflows/document.yaml
+++ b/.github/workflows/document.yaml
@@ -1,15 +1,13 @@
 # Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
+# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
 on:
   push:
-    paths: ["**.[rR]", "**.[qrR]md", "**.[rR]markdown", "**.[rR]nw"]
+    paths: ["R/**"]
 
-name: Style & Document
-
-permissions:
-  contents: write
+name: Document
 
 jobs:
-  document-and-style:
+  document:
     runs-on: ubuntu-latest
     env:
       GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
@@ -27,22 +25,18 @@ jobs:
       - name: Install dependencies
         uses: r-lib/actions/setup-r-dependencies@v2
         with:
-          extra-packages: any::roxygen2, any::styler
-          needs: roxygen2, styler
+          extra-packages: any::roxygen2
+          needs: roxygen2
 
-      - name: Style code
-        run: styler::style_pkg()
-        shell: Rscript {0}
-
-      - name: Generate documentation
+      - name: Document
         run: roxygen2::roxygenise()
         shell: Rscript {0}
 
-      - name: Commit and push all changes
+      - name: Commit and push changes
         run: |
           git config --local user.name "$GITHUB_ACTOR"
           git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
-          git add .
-          git commit -m "Run styler & update documentation" || echo "No changes to commit"
+          git add man/\* NAMESPACE DESCRIPTION
+          git commit -m "Update documentation" || echo "No changes to commit"
           git pull --ff-only
           git push origin
